
export class usermodel {

    public UserDetailsID: number;
    public FirstName: string = "";
    public MatrimonyId: string = "";
    public LastName: string = "";
    public Address: string = "";
    public Email: string = "";
    public Password: string = "";
    public Gender: string = "";
    public DateOfBirth: Date = null;
    public DateOfBirthstr: string = "";
    
    public BodyType: string = "";
    public Complexion: string = "";
    public PhysicalStatus: string = "";
    public Height: string = "";
    public Weight: string = "";
    public MaritalStatus: string = "";
    public NoofChildren: string = "";
    public LanguagesKnown: string = "";
    public MotherTongueId: string = "";
    public ResidingCountryId: string = "";
    public ResidingState: string = "";
    public ResidingCity: string = "";
    public CitizenshipId: string = "";
    public IsActive: string = "";
    public Role: string = "";
    public IsUpgraded: string = "";
    public UpgradeId: string = "";
    public CreatedBy: string = "";
    public CreatedOn: string = "";
    public UpdatedBy: string = "";
    public UpdatedOn: string = "";
    public MobileNo: string = "";
    public PersonDetailsID: number;
    public Religion: string = "";
    public Caste: string = "";
    public SubCaste: string = "";
    public EatingHabit: string = "";
    public Smoking: string = "";
    public DrinkType: string = "";
    public LifeStyle: string = "";
    public Hobbies: string = "";
    public EducationalQualificationId: string = "";
    public NameoftheInstitution: string = "";
    public Occupation: string = "";
    public Designation: string = "";
    public Income: string = "";
    public BusinessType: string = "";
    public Aboutmyself: string = "";
    public FamilyType: string = "";
    public FamilyValues: string = "";
    public FamilyStatus: string = "";
    public FamilyOrigin: string = "";
    public NoofSiblings: string = "";
    public NOofmarriedSiblings: string = "";
    public Fathersoccupation: string = "";
    public Mothersoccupation: string = "";
    public FamilyBusinesstype: string = "";
    public FamilyBusinessTenure: string = "";
    public AboutmyFamily: string = "";
    public Manglik: string = "";
    public HoroscopeAvailable: string = "";
    public Raasi: string = "";
    public Star: string = "";
    public Gothram: string = "";
    public Turnover: string = "";
    public file: string = "";
}
